### ISSUE TITLE
White space ignored in panel

### ISSUE THREAD

**Issue by lloiser** [joefitzgerald/tester-go#26]
Actual:
![actual](https://cloud.githubusercontent.com/assets/3003233/19035045/67343f24-8967-11e6-901d-d6fa3995e620.png)

Expected:
![expected](https://cloud.githubusercontent.com/assets/3003233/19035048/6ae01986-8967-11e6-92df-70dd757039e1.png)

**Comment by joefitzgerald** [comment]
Closing in deference to https://github.com/joefitzgerald/go-plus/issues/555
