### ISSUE TITLE
the atom editor would be have syntax highlight error when tester-go plugin enabled

### ISSUE THREAD

**Issue by gwind** [joefitzgerald/tester-go#31]
Hi,

I've syntax highlight error after upgrade atom to 1.11.x and update tester-go plugin.

atom version:

```
$ atom -v
Atom    : 1.11.2
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0
```

![tester-go](https://cloud.githubusercontent.com/assets/98713/19468370/8263da60-9548-11e6-833c-f6d5f9fbb233.jpg)
![tester-go-syntax-highlight-error](https://cloud.githubusercontent.com/assets/98713/19468371/82643a00-9548-11e6-87ad-cbbe359b0678.jpg)

It's normal when i disable tester-go plugin.

Any ideas ?

Thanks !

**Comment by lloiser** [comment]
The red background indicates that this code is not covered by any tests in this package.
With the latest version of `tester-go` tests will be started (with `-coverprofile` mode) when saving `.go` files. This then causes these red backgrounds all over your code.

Possible solutions:
- disable the setting `Run Tests On Save` (do not run tests on save)
- change `Coverage Highlight Mode` to `disabled`
- add some tests to cover this code 😉

**Comment by gwind** [comment]
Thanks, :smile: 

I'll check again.
