### ISSUE TITLE
not seeing any output from this

### ISSUE THREAD

**Issue by jspiro** [joefitzgerald/tester-go#8]
I have go-plus installed, my paths set up, and on save I see my linter doing its work and reporting errors. All that is good.

But I don't see any output from this tool. I opted into it running on save as well. It appears that tests might be running in the background, but I don't see results or coverage info in the editor. (I'm not sure where it's supposed to go without a screenshot.)

What am I doing wrong?

**Comment by carlisia** [comment]
Same here. I thought in the past it showed code that had test coverage in green and otherwise red? Right? I stopped doing Go for a while and now this is driving me crazy, I need my coverage indicator. :)

**Comment by joefitzgerald** [comment]
Make sure your tests are passing first. `go test ./...` from the terminal in any package where you don't see coverage. Display of test output / pass / fail forthcoming.

**Comment by jspiro** [comment]
#10 might have been the trick for me. Still knowing when it's running and whether tests passed would be hugely valuable, but it's working mostly for me now!
